### ISSUE TITLE
Migrate to Unsplash API

### ISSUE THREAD

**Issue by sevmonster** [nextcloud/unsplash#115]
Currently, the app just replaces the background image with a `source.unsplash.com` URI. These endpoints are [deprecated](https://changelog.unsplash.com/deprecations/2021/11/25/source-deprecation.html) and should be replaced with [API calls](https://unsplash.com/documentation#get-a-random-photo).

More context: https://www.reddit.com/r/unsplash/comments/s13x4h/comment/hu2ztml

Note that implementing this requires #9 to comply with section 6 of the [API terms](https://unsplash.com/api-terms) and as such [Unsplash API guidelines, Technical Guidelines, point 3](https://help.unsplash.com/en/articles/2511245-unsplash-api-guidelines#technical-guidelines). Unless the server administrator registers their own API key, the API guidelines must also be followed in full to apply for production rate limits.

**Comment by JojoBr0** [comment]
since yesterday on my instances I have the problem that through the deprecation of `source.unsplash.com` I can't get background images from unsplash any more.
Are there plans to implement unsplash support via their api?

**Comment by JojoBr0** [comment]
okay thanks👍, changing the provider is the workaround i have already done.

**Comment by newhinton** [comment]
Okay, i will not be able to implement this in the next weeks. I am extremely busy, and to do this properly i have to implement quite a few things:

- Dynamic Provider Configuration (to allow adding an api-key, and keywords, etc.)
- Caching (to show urls/attributions)

Both will take time that i dont have due to finals, but i have not forgotten about this and will implement it in the upcoming months.
