### ISSUE TITLE
l10n: Splitted text strings confusing translators

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/unsplash#136]
On Transifex there is no way to get the relation of part strings like

https://github.com/nextcloud/unsplash/blob/69fe57a2ff60ab82fdf8cfd4e5c529017b6b9b11/templates/settings/admin.php#L91

Please improve.

Reported at Transifex.

**Comment by newhinton** [comment]
Oh, yeah sorry. I have improved the string so that it is more or less self-contained.

> "You should not need to apply for production"

The linked page asks the user to apply for production usage of their newly generated api token. For this usage, this is not really required since we access their api only once a day, which is squarely in their 50hits/h limit for the demo application.

I am not sure if i can provide more context here, since the context is on an external site.
