### ISSUE TITLE
Hard to read text in header

### ISSUE THREAD

**Issue by krejcar25** [nextcloud/unsplash#62]
With some images the labels of apps in header are hard to read as the text is transparent a little. It might help to put some kind of darkish transparent-ish background to them if the header images are enabled.

![Screenshot 2020-06-08 at 7 40 58 PM](https://user-images.githubusercontent.com/7903442/84062867-513d2c80-a9c0-11ea-9714-3db5c9d656df.png)
vs.
![Screenshot 2020-06-08 at 7 48 07 PM](https://user-images.githubusercontent.com/7903442/84063234-07a11180-a9c1-11ea-88af-e1a662cf0f9e.png)

I just added `background: rgba(50, 50, 50, 0.7);` to the `ul#appmenu`, which holds the buttons and it doesn't look too bad I think.

**Comment by tamburra** [comment]
Nextcloud has there own gradient that shows up when you scroll 70px down the screen.  You can change this value to 0px instead to always keep the gradient.
```
#header::before {
    margin-top: 0px !important;
}
```
<img width="1440" alt="Screen Shot 2021-01-23 at 9 55 24 PM" src="https://user-images.githubusercontent.com/16267805/105619972-bf0a5d00-5dc5-11eb-8257-a56d81fcac7f.png">

**Comment by newhinton** [comment]
This is not really fixable. Since we cant control the image, we often get such artifacts. I am closing this for now, but if i find a solution to that i will implement it. If someone knows css-magic that can change a color based on its background, please comment!

If you want to always show a backgroundgradient or something else, you should use the custom-css app.
