### ISSUE TITLE
Translation in Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/unsplash#85]
I propose to add a project for translation in Transifex. You can do this with your team or submit a request to join the Nextcloud team. This will allow you to systematically translate the added text strings and translate into multiple languages :wink:.

**Comment by newhinton** [comment]
@comradekingu Why did you downvote this? Are there any reasons not to do this?

**Comment by comradekingu** [comment]
@newhinton There is nothing systematic or consistent about it.
Every time it has been tried it goes off the rails on account of Transifex being the possibly worst platform available. Not only in terms of functionality btw.
For whatever synergy you could hope to get (something that also happens to be broken), why not instead replicate the individual successes of Nextcloud projects on Weblate?

That being said, the only string I think will fail here here is "These images are provided %s by %s.", depending on the language.

**Comment by newhinton** [comment]
I have not used any platform for translations, so i will have to find out how either works, so i can't really judge your comment. I will probably still go with transifex, because the nextcloud project heavily relies on that and so i probably can get unsplash into the nextcloud-project there. 

But thank you for your input anyway, i will definitively try other sites like weblate in future projects!

**Comment by Valdnet** [comment]
> I will probably still go with transifex, because the nextcloud project heavily relies on that and so i probably can get unsplash into the nextcloud-project there.

Exactly. The joint team also allows the unification of translations and text strings in applications.

**Comment by p-bo** [comment]
...and gain benefits from work of whole Nextcloud translators community for users of your app please?

For instance:

- much more translators will get involved, because without it, they will newer even know about possibility to translate this app - example of benefits for project known in this manner for community of Nextcloud translators (app with recently added to this workflow, based on same request as this one): https://github.com/H2CK/oidc/commit/937fc37d7797fecc9f4f49e12a154cd8987cf99c (se this and ongoing Nextcloud bot commits - translation of app is getting completed/improved in no time)
- also, as app is evolving, when some string(s) in app is/are changed/added, in case of continuous translation workflow translators are noticed intermediately and strings are translated before new version is released. In contrast with situation, that this change (in source strings) is only silently published in git repo and no one will (get) notice(d) till never version with untranslated strings get released (proactive vs retroactive).
- when one (of translators) will during using this app notice possibility to translate something in better manner, it is much efficient (especially for minor changes) to do this in translation tool than edit file directly in git. For example in case of one letter changes (misspelled words, etc.) has change directly in git such overhead (many steps to change just one letter), that these type of tweaks are rare due this (loss of quality for users)

To conclude: with continuous translation workflow, result is, that users of your app are getting more complete and more polished localization, so their user experience is much more pleasant.

**Comment by newhinton** [comment]
@comradekingu I have read your comment but i cannot really judge your comment factually, but i agree that generally nextcloud should use the most open&easy to use platform.

That said, i still went with transifex for multiple reasons:

1. Transifex is widely used by nextcloud, and therefore the know-how is at transifex.
2. Maintaining a different platform is additional work that i would have to do, now i can "offload" it to the nextcloud-community
3. I dont actually have the knowledge over alternatives, so i would have to do research

In the end i went the path of least resistance and i hope it will lead to great success regardless.

But thanks for your input!
